spring:
  application:
    name: mdsl-institution-service
  profiles:
    default: dev  
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson: 
    default-property-inclusion: NON_NULL
    property-naming-strategy: com.mdsl.institution.util.MDSLPropertyNamingStrategy$MDSLPropertyNamingKeepAsIs
    
       
server:
  servlet:
    context-path: /api
  port: 8090