spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MDSL
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #create-drop 
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
      
JWT_CONFIG: {"secretKey": "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970", "expiration": "86400000", "refreshToken": {"expiration": "604800000"}}
        
server:
  port: 8090