spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: none
    database: ${DB_PROVIDER}
    database-platform: ${DB_PLATFORM}
    
    
server:
  port: ${PORT_NUMBER}       